version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    command: flask run --host=0.0.0.0

  mongo:
    image: mongo
    restart: always
    hostname: test_mongodb
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
